### ISSUE TITLE
Exhaustive Mention Span Detection Config

### ISSUE THREAD

**Issue by qiwei-404** [kingsaint/BioMedical-EL#12]
You mentioned in your paper:
"Following the recent work of Kolitsas et al. (2018) and Li et al. (2020), our mention span detection method enumerates all possible spans in the input text document as potential mentions. However, enumerating all possible spans in a document of length T is prohibitively large (O(T^2)) and computationally expensive. Therefore, we constrain the maximum length of a mention span to L << T."

Could you clarify the value of L you used in your experiments, and how I could set the value of L in the source code? Thank you very much.

**Comment by kingsaint** [comment]
> You mentioned in your paper: "Following the recent work of Kolitsas et al. (2018) and Li et al. (2020), our mention span detection method enumerates all possible spans in the input text document as potential mentions. However, enumerating all possible spans in a document of length T is prohibitively large (O(T^2)) and computationally expensive. Therefore, we constrain the maximum length of a mention span to L << T."
> 
> Could you clarify the value of L you used in your experiments, and how I could set the value of L in the source code? Thank you very much.

Hi @qiwei-404, Sorry for the delayed response. L can be set to the value of your choice by providing the argument `--max_mention_length`. The default value for this is set to 20.
