### ISSUE TITLE
GPU Specs

### ISSUE THREAD

**Issue by coltonflowers1** [kingsaint/BioMedical-EL#3]
Would you mind posting the GPU specs which were used to produce the original results in the paper? I am trying to get this to work with 16 GB, but I keep getting a CUDA OOM error.

**Comment by kingsaint** [comment]
It is mentioned in the paper. We used 4 NVIDIA Quadro RTX GPUs with 24 GB memory for training and 1 GPU for inference.

**Comment by coltonflowers1** [comment]
I see now that you did include it in the paper, thanks!
