### ISSUE TITLE
How often does negative mining occur during training?

### ISSUE THREAD

**Issue by coltonflowers1** [kingsaint/BioMedical-EL#5]
Unless I'm overlooking something, it seems that after every epoch if we are performing hard-negative mining, a new training set is created after every epoch, supposedly so that our new dataset contains the hard negatives corresponding to the new model. However, this training set is reloaded from cache unless args.overwrite_cache is set to true. This would mean that if this flag isn't set to true, hard negatives are mined only using the initial model and then reused after every epoch, instead of iteratively produced as training progresses, as is outlined in Gillick, 2019. Is this flag meant to trigger the iterative hard negative mining? If not, how did hard negative mining work in the architectures used to yield the numbers outlined in the paper?

**Comment by kingsaint** [comment]
You are right. We need to set args.overwrite_cache to true for hard negative mining after every epoch.
