### ISSUE TITLE
Documentation of setup for BioBERT and neleval

### ISSUE THREAD

**Issue by phlobo** [kingsaint/BioMedical-EL#7]
First of all, thanks for sharing this repo!

However, I have a bit of trouble reproducing the results, maybe you can help.

1. Running the training script

`python run_e2e_span.py  --data_dir data/BC5CDR/processed_data --model_type bert --output_dir o utput --do_train --n_gpu 1 --model_name_or_path ./biobert_v1.1_pubmed`

yields different errors.

If I use the BioBERT checkpoint from here https://github.com/dmis-lab/biobert:
I get the error: `OSError: file ./biobert_v1.1_pubmed/config.json not found`

If, however, I use this checkpoint https://huggingface.co/dmis-lab/biobert-v1.1/tree/main
I'm getting `OSError: Error no file named ['pytorch_model-1000000.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory ./biobert-v1.1/ or from_tf set to False`

2. neleval

The Readme states that evaluation is run with `./neleval/BC5CDR-AllSpan/gold.csv`. How do I get this file? Is it some produced as part of running the e2e_span script?

Thanks in advance!

**Comment by kingsaint** [comment]
Hi, 

Thanks for your interest in our paper.
1. - If you are using https://github.com/dmis-lab/biobert, please rename the `bert_config.json` file in `./biobert_v1.1_pubmed` to `config.json`. Alternatively, you can specify the path to the config file using the `--config_name` argument in the training script.
    - If you are using https://huggingface.co/dmis-lab/biobert-v1.1/tree/main, please rename `pytorch_model.bin` to `pytorch_model-1000000.bin`. 
2. `gold.csv` will be created when you do inference on the trained model. Use the `--do_eval` argument to do so. Then copy the `gold.csv` file to a directory named `BC5CDR-AllSpan`.

I hope this is helpful.

**Comment by phlobo** [comment]
Thank you so much! Regarding 1. I tried the second option (using the HuggingFace model) and actually progressed a bit further. However, now I am getting an error

```
01/25/2022 12:12:17 - INFO - __main__ -   Loading features from cached file data/BC5CDR/processed_data/cached_train_biobert-v1.1
Traceback (most recent call last):
  File "run_e2e_span.py", line 1071, in <module>
    main()
  File "run_e2e_span.py", line 1021, in main
    global_step, tr_loss = train(args, model, tokenizer)
  File "run_e2e_span.py", line 76, in train
    train_dataset, _, _ = load_and_cache_examples(args, tokenizer)
  File "run_e2e_span.py", line 725, in load_and_cache_examples
    all_mention_start_indices = torch.tensor([f.mention_start_indices for f in features], dtype=torch.long)
ValueError: expected sequence of length 16 at dim 1 (got 9)
```

Do you have any hints what might be the problem?

The command I run is `python run_e2e_span.py  --data_dir data/BC5CDR/processed_data/ --model_type bert --model_name_or_path biobert-v1.1 --output_dir output --do_train`

**Comment by kingsaint** [comment]
use `--overwrite_output_dir`, `--overwrite_cache`, and `--use_hard_and_random_negative` during training. During inference use `--use_all_candidates`
